blog_engine/blog_engine/urls.py
from functools import partial

from django.contrib import admin
from django.urls import path, include
from django.views.defaults import permission_denied

from . import user_urls
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/change_password', views.PasswordChangeView.as_view(), name="change_password"),
    path('accounts/signup', views.signup, name="register"),
    path("", views.PostsView.as_view(), name="index"),
    path('accounts/', include('django.contrib.auth.urls',)),
    path('profile/', include(user_urls)),
    path('content/', include('content.urls')),
    path('search/', views.PostSearchView.as_view(), name='search')
]

handler403 = partial(permission_denied, template_name="shared/no_permission.html")

blog_engine/content/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("new_post/", views.new_post, name="newpost"),
    path("delete_post/<int:post_id>", views.delete_post, name="delete_post"),
    path("view_post/<int:post_id>", views.view_post, name="view_post"),
    path("edit_post/<int:post_id>", views.edit_post, name="edit_post"),
    path("view_post/<int:post_id>/new_comment", views.new_comment, name="new_comment"),
    path("view_post/<int:post_id>/edit_comment/<int:comment_id>", views.edit_comment, name="edit_comment"),
    path("view_post/<int:post_id>/delete_comment/<int:comment_id>", views.delete_comment, name="delete_comment"),
]

blog_engine/content/models.py
from django.conf import settings
from django.contrib.auth.models import User
from django.db import models
# Create your models here.
from django.utils import timezone


class Tag(models.Model):
    name = models.CharField(max_length=30)
    description = models.TextField()

    def __str__(self):
        return self.name


class Post(models.Model):
    title = models.CharField(max_length=100)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.TextField()
    post_date = models.DateTimeField(default=timezone.now)
    last_update = models.DateTimeField(auto_now=True)
    tags = models.ManyToManyField(Tag, blank=False, )

    class Meta:
        unique_together = ('title', 'author')

    def __str__(self):
        return f"Author: {self.author}, Title: {self.title}"


class Comment(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, blank=True, null=True)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    content = models.TextField()
    published = models.DateTimeField(auto_now_add=True)

blog_engine/templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link href="{% static "css/bootstrap.css" %}" rel="stylesheet"/>
    <link href="{% static "css/styles.css" %}" rel="stylesheet"/>
    <script src="{% static 'js/bootstrap.js' %}"></script>

    <meta charset="UTF-8">
    <title>{% block title %} {% endblock %}</title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'index' %}">Django blog</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'index' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            {% if perms.content.add_post %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url "newpost" %}">New Post</a>
                </li>
            {% endif %}

            {% if user.is_authenticated and not user_posts_only %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url "show_user_posts" %}">Your Posts</a>
                </li>
            {% endif %}
        </ul>
        <ul class="navbar-nav no-right">
            {% if perms.content.add_post %}

            {% endif %}

            {% if user.is_staff %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'admin:index' %}">Admin panel</a>
                </li>
            {% endif %}



            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'show_profile' %}"> {{ user.username }} </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}">Sign Out</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login' %}">Sign In</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'register' %}">Don't have an account?</a>
                </li>
            {% endif %}


        </ul>
    </div>
</nav>

{% block content %}
{% endblock %}


</body>
</html>